In [4]:
pip install pandas 

You should consider upgrading via the '/Users/hiteshallakki/Documents/DataTalks/jupyter_env/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd

In [6]:
import requests

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
response = requests.get(url)

with open("car_fuel_efficiency.csv", "wb") as f:
    f.write(response.content)


/Users/hiteshallakki/Documents/DataTalks/jupyter_env/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [7]:
import pandas as pd

# Load the saved CSV file
df = pd.read_csv("car_fuel_efficiency.csv")

# Peek at the first few rows
print(df.head())

# Optional: check structure of dataset
print(df.info())


   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3         

In [8]:
import numpy as np

import matplotlib.pyplot as plt

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

In [10]:
df.columns = df.columns.str.lower().str.replace(' ' ,'_')

In [11]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [12]:
categorical_columns = list(df.dtypes[df.dtypes =='object'].index)

In [13]:
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ' , '_')

In [14]:
#1 number of values
df.count()

engine_displacement    9704
num_cylinders          9222
horsepower             8996
vehicle_weight         9704
acceleration           8774
model_year             9704
origin                 9704
fuel_type              9704
drivetrain             9704
num_doors              9202
fuel_efficiency_mpg    9704
dtype: int64

In [15]:
# number of unique values
df['fuel_type'].nunique()

2

In [16]:
# missing values
df.isnull().sum().sum()

np.int64(2622)

In [17]:
df[df["origin"]=="asia"]["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

In [18]:
df.loc[df[df["origin"] == "asia"]["fuel_efficiency_mpg"].idxmax()]



engine_displacement                  330
num_cylinders                        3.0
horsepower                         136.0
vehicle_weight               1223.298226
acceleration                         NaN
model_year                          2001
origin                              asia
fuel_type                       gasoline
drivetrain             front-wheel_drive
num_doors                            1.0
fuel_efficiency_mpg            23.759123
Name: 9387, dtype: object

In [19]:
# Find the median value of horsepower column in the dataset.
# Next, calculate the most frequent value of the same horsepower column.
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.
# Has it changed?

# Yes, it increased
# Yes, it decreased
# No


In [20]:
df['horsepower'].median()

np.float64(149.0)

In [21]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [22]:
mode = df['horsepower'].mode()
df['horsepower'] = df['horsepower'].fillna(mode)

In [23]:
df['horsepower'].median()

np.float64(149.0)

In [24]:
#answer NO

In [27]:
# Select all the cars from Asia
# Select only columns vehicle_weight and model_year
# Select the first 7 values
# Get the underlying NumPy array. Let's call it X.
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# Invert XTX.
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the sum of all the elements of the result?
# Note: You just implemented linear regression. We'll talk about it in the next lesson.
# 0.051
# 0.51
# 5.1
# 51


In [37]:
df_asia = df[df['origin'] == 'asia']


In [39]:
df_selected = df_asia[['vehicle_weight','model_year']]
df_asia[['vehicle_weight','model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [41]:
df_subset = df_selected.head(7)

In [43]:
X = df_subset.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [47]:
#matrix multiplication
XTX = np.dot(X.T,X)
XTX

array([[62248334.33150761, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [48]:
#Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [49]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])


In [51]:
#multiplying the results
w = XTX_inv.dot(X.T).dot(y)
w


array([0.01386421, 0.5049067 ])

In [54]:
result_sum = w.sum()
result_sum

np.float64(0.5187709081074006)